permalink: pretty
collections:
  pages:
    output: true
    permalink: /:path/

# Site settings
title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""  # Leave blank since this is a user page repo
url: "https://kohlmanh.github.io"  # Your GitHub Pages site URL
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima  # Or remove this line if not using a theme

# Markdown processor
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files/folders from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

# Directory for non-gem plugins
plugins_dir: _plugins

# Serve static files
include:
  - assets/pdfs/
  - assets/videos/
